(set-frame-parameter nil 'fullscreen 'fullboth)
(setq inhibit-startup-screen    t)
(setq inhibit-splash-screen     t)
(setq make-backup-files         nil)
(setq x-select-enable-clipboard t)
(setq gc-cons-threshold 100000000)
(setq read-process-output-max (* 1024 1024))
(menu-bar-mode         -1)
(tool-bar-mode         -1)
(scroll-bar-mode       -1)
(delete-selection-mode 1)
(defalias 'yes-or-no-p 'y-or-n-p)

(provide 'init-builtin)
